<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Infrastructure</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Wrappers\JsonSerializer.vb~RF8e4e763.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.vbproj" />
  </ItemGroup>

</Project>
